[build]
  base = "frontend"
  command = "npx react-router build"
  publish = "build/client"

[[redirects]]
  from = "/api/*"
  to = "https://study-circle-production-55ec.up.railway.app/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200