// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/blog": {
    params: {};
  };
  "/contact": {
    params: {};
  };
  "/privacy": {
    params: {};
  };
  "/terms": {
    params: {};
  };
  "/guidelines": {
    params: {};
  };
  "/verify-email": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/dashboard/groups": {
    params: {};
  };
  "/dashboard/groups/:groupId": {
    params: {
      "groupId": string;
    };
  };
  "/dashboard/groups/:groupId/chat": {
    params: {
      "groupId": string;
    };
  };
  "/dashboard/chat": {
    params: {};
  };
  "/dashboard/sessions": {
    params: {};
  };
  "/dashboard/resources": {
    params: {};
  };
  "/dashboard/progress": {
    params: {};
  };
  "/dashboard/friends": {
    params: {};
  };
  "/dashboard/library": {
    params: {};
  };
  "/dashboard/profile": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/about" | "/blog" | "/contact" | "/privacy" | "/terms" | "/guidelines" | "/verify-email" | "/dashboard" | "/dashboard/groups" | "/dashboard/groups/:groupId" | "/dashboard/groups/:groupId/chat" | "/dashboard/chat" | "/dashboard/sessions" | "/dashboard/resources" | "/dashboard/progress" | "/dashboard/friends" | "/dashboard/library" | "/dashboard/profile";
  };
  "layout/app_layout.tsx": {
    id: "layout/app_layout";
    page: "/" | "/about" | "/blog" | "/contact" | "/privacy" | "/terms" | "/guidelines" | "/verify-email";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/about.tsx": {
    id: "routes/about";
    page: "/about";
  };
  "routes/blog.tsx": {
    id: "routes/blog";
    page: "/blog";
  };
  "routes/contact.tsx": {
    id: "routes/contact";
    page: "/contact";
  };
  "routes/legal/privacy.tsx": {
    id: "routes/legal/privacy";
    page: "/privacy";
  };
  "routes/legal/terms.tsx": {
    id: "routes/legal/terms";
    page: "/terms";
  };
  "routes/legal/guidelines.tsx": {
    id: "routes/legal/guidelines";
    page: "/guidelines";
  };
  "routes/verify-email.tsx": {
    id: "routes/verify-email";
    page: "/verify-email";
  };
  "layout/dashboard_layout.tsx": {
    id: "layout/dashboard_layout";
    page: "/dashboard" | "/dashboard/groups" | "/dashboard/groups/:groupId" | "/dashboard/groups/:groupId/chat" | "/dashboard/chat" | "/dashboard/sessions" | "/dashboard/resources" | "/dashboard/progress" | "/dashboard/friends" | "/dashboard/library" | "/dashboard/profile";
  };
  "routes/dashboard/index.tsx": {
    id: "routes/dashboard/index";
    page: "/dashboard";
  };
  "routes/dashboard/groups.tsx": {
    id: "routes/dashboard/groups";
    page: "/dashboard/groups";
  };
  "routes/dashboard/group_detail.tsx": {
    id: "routes/dashboard/group_detail";
    page: "/dashboard/groups/:groupId";
  };
  "routes/dashboard/group_chat.tsx": {
    id: "routes/dashboard/group_chat";
    page: "/dashboard/groups/:groupId/chat";
  };
  "routes/dashboard/general_chat.tsx": {
    id: "routes/dashboard/general_chat";
    page: "/dashboard/chat";
  };
  "routes/dashboard/sessions.tsx": {
    id: "routes/dashboard/sessions";
    page: "/dashboard/sessions";
  };
  "routes/dashboard/resources.tsx": {
    id: "routes/dashboard/resources";
    page: "/dashboard/resources";
  };
  "routes/dashboard/progress.tsx": {
    id: "routes/dashboard/progress";
    page: "/dashboard/progress";
  };
  "routes/dashboard/friends.tsx": {
    id: "routes/dashboard/friends";
    page: "/dashboard/friends";
  };
  "routes/dashboard/library.tsx": {
    id: "routes/dashboard/library";
    page: "/dashboard/library";
  };
  "routes/dashboard/profile.tsx": {
    id: "routes/dashboard/profile";
    page: "/dashboard/profile";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "layout/app_layout": typeof import("./app/layout/app_layout.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/about": typeof import("./app/routes/about.tsx");
  "routes/blog": typeof import("./app/routes/blog.tsx");
  "routes/contact": typeof import("./app/routes/contact.tsx");
  "routes/legal/privacy": typeof import("./app/routes/legal/privacy.tsx");
  "routes/legal/terms": typeof import("./app/routes/legal/terms.tsx");
  "routes/legal/guidelines": typeof import("./app/routes/legal/guidelines.tsx");
  "routes/verify-email": typeof import("./app/routes/verify-email.tsx");
  "layout/dashboard_layout": typeof import("./app/layout/dashboard_layout.tsx");
  "routes/dashboard/index": typeof import("./app/routes/dashboard/index.tsx");
  "routes/dashboard/groups": typeof import("./app/routes/dashboard/groups.tsx");
  "routes/dashboard/group_detail": typeof import("./app/routes/dashboard/group_detail.tsx");
  "routes/dashboard/group_chat": typeof import("./app/routes/dashboard/group_chat.tsx");
  "routes/dashboard/general_chat": typeof import("./app/routes/dashboard/general_chat.tsx");
  "routes/dashboard/sessions": typeof import("./app/routes/dashboard/sessions.tsx");
  "routes/dashboard/resources": typeof import("./app/routes/dashboard/resources.tsx");
  "routes/dashboard/progress": typeof import("./app/routes/dashboard/progress.tsx");
  "routes/dashboard/friends": typeof import("./app/routes/dashboard/friends.tsx");
  "routes/dashboard/library": typeof import("./app/routes/dashboard/library.tsx");
  "routes/dashboard/profile": typeof import("./app/routes/dashboard/profile.tsx");
};