// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/dashboard/groups": {
    params: {};
  };
  "/dashboard/sessions": {
    params: {};
  };
  "/dashboard/resources": {
    params: {};
  };
  "/dashboard/progress": {
    params: {};
  };
  "/dashboard/friends": {
    params: {};
  };
  "/dashboard/library": {
    params: {};
  };
  "/dashboard/profile": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/dashboard" | "/dashboard/groups" | "/dashboard/sessions" | "/dashboard/resources" | "/dashboard/progress" | "/dashboard/friends" | "/dashboard/library" | "/dashboard/profile";
  };
  "layout/app_layout.tsx": {
    id: "layout/app_layout";
    page: "/";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "layout/dashboard_layout.tsx": {
    id: "layout/dashboard_layout";
    page: "/dashboard" | "/dashboard/groups" | "/dashboard/sessions" | "/dashboard/resources" | "/dashboard/progress" | "/dashboard/friends" | "/dashboard/library" | "/dashboard/profile";
  };
  "routes/dashboard/index.tsx": {
    id: "routes/dashboard/index";
    page: "/dashboard";
  };
  "routes/dashboard/groups.tsx": {
    id: "routes/dashboard/groups";
    page: "/dashboard/groups";
  };
  "routes/dashboard/sessions.tsx": {
    id: "routes/dashboard/sessions";
    page: "/dashboard/sessions";
  };
  "routes/dashboard/resources.tsx": {
    id: "routes/dashboard/resources";
    page: "/dashboard/resources";
  };
  "routes/dashboard/progress.tsx": {
    id: "routes/dashboard/progress";
    page: "/dashboard/progress";
  };
  "routes/dashboard/friends.tsx": {
    id: "routes/dashboard/friends";
    page: "/dashboard/friends";
  };
  "routes/dashboard/library.tsx": {
    id: "routes/dashboard/library";
    page: "/dashboard/library";
  };
  "routes/dashboard/profile.tsx": {
    id: "routes/dashboard/profile";
    page: "/dashboard/profile";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "layout/app_layout": typeof import("./app/layout/app_layout.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "layout/dashboard_layout": typeof import("./app/layout/dashboard_layout.tsx");
  "routes/dashboard/index": typeof import("./app/routes/dashboard/index.tsx");
  "routes/dashboard/groups": typeof import("./app/routes/dashboard/groups.tsx");
  "routes/dashboard/sessions": typeof import("./app/routes/dashboard/sessions.tsx");
  "routes/dashboard/resources": typeof import("./app/routes/dashboard/resources.tsx");
  "routes/dashboard/progress": typeof import("./app/routes/dashboard/progress.tsx");
  "routes/dashboard/friends": typeof import("./app/routes/dashboard/friends.tsx");
  "routes/dashboard/library": typeof import("./app/routes/dashboard/library.tsx");
  "routes/dashboard/profile": typeof import("./app/routes/dashboard/profile.tsx");
};